apiVersion: v1
kind: Service
metadata:
  name: immich-valkey
spec:
  selector:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: valkey
  ports:
    - name: redis
      port: 6379
      targetPort: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-valkey
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: immich
      app.kubernetes.io/component: valkey
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich
        app.kubernetes.io/component: valkey
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: valkey
          image: docker.io/valkey/valkey:9@sha256:8e8d64b405ce18f41b8e5ee20aa4687a8ed0022d1298f2ce31cdcf3a76e09411
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli ping | grep -q PONG
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli ping | grep -q PONG
            periodSeconds: 30