apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minecraft-local-retain
  volumeName: minecraft-data
  resources:
    requests:
      storage: 100Gi
