apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: immich-local-retain
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: library
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: immich-local-retain
  local:
    path: /mnt/data-drive-2tb/homelab/immich/library
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - krof-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-postgres
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: postgres
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: immich-local-retain
  local:
    path: /mnt/data-drive-2tb/homelab/immich/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - krof-desktop
