apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minecraft-local-retain
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-data
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/component: data
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minecraft-local-retain
  local:
    path: /mnt/data-drive-2tb/homelab/minecraft
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - krof-desktop
