apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
    annotations:
        argocd.argoproj.io/sync-options: Prune=false,Delete=false
type: Opaque
data:
    client_id: ENC[AES256_GCM,data:aLvqYV6teOf2EBwPH5nVWTMv+vpKcCOD,iv:IpVBxeHUsgpzarPA+TcNfSxvwo2VCMInIm99thgvp98=,tag:ymOGFed3UOT5+wXAD1mR0A==,type:str]
    client_secret: ENC[AES256_GCM,data:vG/gB0hc+aAT/RdpCQkHsnugFgc8d4T9OT8QMLC80PXi1Lwsd1+TWNCRwNNWirRM2UzAOoL0bsmHmNuRpe3zx9nNLryJWzT/bqei4k9NuoNjTO0kMleW4g==,iv:VQmEpgSH7PsbAelRsZAx2FguljCaHAgx0xH2aXXloFw=,tag:EYTK1/7ysTHHije0bVGelA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMU9WTHN1cG1RUE42bkJv
            UkU3ekVkRFMweWhhWUk4blpPaWdDK2FWSWhrCkIyTGlGVVExK2pGK3hzWFdQa3Z6
            SXJPMDBPUWFPbkszTThSc3llN1hXL0EKLS0tIGI5SndoSDVJTUtqUWpzcTBpU0pI
            WFFGUmdWRWdSZjdhaE1DWEFWYW9ub2MK74m07zlYjEWXsUR7INX9REKgcZQXVJHD
            3tmgo2d645xWWrICpW9RLJUn9CPs8RuKIglMv1Jm/ixSz2nO8Bfcjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjc8lptxy8te9xp9gpfwxxrnkqex6xuhu5crwu6jktuze0gyyfkqrc63eg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T14:35:29Z"
    mac: ENC[AES256_GCM,data:/IGxsNpTfeUWXj4u4XWBkZZvnD72c1u0BTGxQCnixCNPtKyNsvMbyjOndOQ0FnC4N+KtOpblnPWmpANhhPttvPb0s8hsXoM1hQ12mXuFZ7vukEVK+qlWvbELIjshyMh9/RE4VoqlaTJI0w5bh3Ah6hkt9jJOE2abCWzec5/zL3w=,iv:p7N0Zs04PPZseKdy07DAkSZ34qjJ/QHupf+Kz7PsiXU=,tag:zS66VyABHn8f+I2X4ktbaw==,type:str]
    version: 3.13.3
