apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: 1.98.9
    helm:
      releaseName: tailscale-operator
      values: |-
        operatorConfig:
          hostname: krof-desktop-k8s-operator
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi

        proxyConfig:
          defaultTags: tag:k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true